version: 2

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: rf
    binary: rf
    main: .
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/drdanmaggs/rocket-fuel/cmd.Version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^style:"
      - "Merge pull request"
  groups:
    - title: Features
      regexp: "^.*feat.*:+.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix.*:+.*$"
      order: 1
    - title: Refactoring
      regexp: "^.*refactor.*:+.*$"
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: drdanmaggs
    name: rocket-fuel
  draft: false
  prerelease: auto
  name_template: "Rocket Fuel v{{.Version}}"
